kind = "web"
previewPath = "/"
title = "Paname City"
version = "1.0.0"
id = "artifacts/paname-city"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21042

[services.development]
run = "pnpm --filter @workspace/paname-city run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/paname-city", "run", "build" ]
publicDir = "artifacts/paname-city/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21042"
BASE_PATH = "/"
